name: mi_bussv
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  latlong2:
  location:
  http:
  geolocator: ^9.0.2
  flutter_map: ^7.0.2
  url_launcher: ^6.0.20
  flutter_osm_plugin: ^1.3.0

  get: ^4.6.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/fonts/Bitter-VariableFont_wght.ttf
    - assets/fonts/Bitter-Italic-VariableFont_wght.ttf
    - assets/images/

  fonts:
    - family: Bitter
      fonts:
        - asset: assets/fonts/Bitter-VariableFont_wght.ttf
        - asset: assets/fonts/Bitter-Italic-VariableFont_wght.ttf
          style: italic

